[package]
name = "kfme"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
byteorder = "1.5.0"
clap = { version = "4.5.20", features = ["derive"] }
indoc = "2.0.5"
regex = "1.11.1"
serde = { version = "1.0.213", features = ["derive"] }
serde_yaml = "0.9"
tera = "1.20.0"
